### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by alchu4n** [tangxiaofeng7/Fofa-collect#11]
配置好邮箱和key以后，执行搜索报错
![image](https://user-images.githubusercontent.com/97670155/151317075-9d9acf34-0e29-45b7-8b71-20a4bd100426.png)

`
java -jar FofaCollect.jar
2022-01-27 16:05:33.173 java[45215:3953633] TSM AdjustCapsLockLEDForKeyTransitionHandling - _ISSetPhysicalKeyboardCapsLockLED Inhibit
java.net.UnknownHostException: fofa.so
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
	at com.r4v3zn.fofa.core.util.HttpUtils.doGet(HttpUtils.java:54)
	at com.r4v3zn.fofa.core.client.FofaClient.getUser(FofaClient.java:66)
	at com.suyu.controller.FofaController.go(FofaController.java:72)
	at com.suyu.controller.FofaController.access$000(FofaController.java:19)
	at com.suyu.controller.FofaController$GoThread.run(FofaController.java:115)
java.lang.NullPointerException
	at com.r4v3zn.fofa.core.client.FofaClient.getUser(FofaClient.java:68)
	at com.suyu.controller.FofaController.go(FofaController.java:72)
	at com.suyu.controller.FofaController.access$000(FofaController.java:19)
	at com.suyu.controller.FofaController$GoThread.run(FofaController.java:115)
java.net.UnknownHostException: fofa.so
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
	at com.r4v3zn.fofa.core.util.HttpUtils.doGet(HttpUtils.java:54)
	at com.r4v3zn.fofa.core.client.FofaClient.getData(FofaClient.java:175)
	at com.r4v3zn.fofa.core.client.FofaClient.getData(FofaClient.java:116)
	at com.suyu.controller.FofaController.go(FofaController.java:80)
	at com.suyu.controller.FofaController.access$000(FofaController.java:19)
	at com.suyu.controller.FofaController$GoThread.run(FofaController.java:115)
Exception in thread "Thread-5" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at com.suyu.controller.FofaController.go(FofaController.java:85)
	at com.suyu.controller.FofaController.access$000(FofaController.java:19)
	at com.suyu.controller.FofaController$GoThread.run(FofaController.java:115)
`

![image](https://user-images.githubusercontent.com/97670155/151317401-9b19109a-5698-47b4-a948-a67260718e70.png)

![image](https://user-images.githubusercontent.com/97670155/151317494-390a2502-c8c2-4457-9136-a29075f7c4ba.png)

**Comment by alchu4n** [comment]
done
